from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import requests
import io
import os
from PIL import Image, ImageDraw, ImageFilter
from psd_tools import PSDImage

app = Flask(__name__)
CORS(app)

REMOVE_BG_API_KEY = os.environ.get("REMOVE_BG_API_KEY")

@app.route("/")
def health():
    return jsonify({"status": "ok", "service": "LayerAI Python PSD", "version": "1.0.0"})

@app.route("/health")
def health_check():
    return jsonify({"status": "ok"})

@app.route("/generate-psd", methods=["POST"])
def generate_psd():
    try:
        if "image" not in request.files:
            return jsonify({"error": "No image uploaded"}), 400

        image_file = request.files["image"]
        image_bytes = image_file.read()

        # Step 1 — Original image load karo
        original_image = Image.open(io.BytesIO(image_bytes)).convert("RGBA")
        width, height = original_image.size

        # Step 2 — Remove.bg se subject nikalo
        subject_image = None
        try:
            response = requests.post(
                "https://api.remove.bg/v1.0/removebg",
                files={"image_file": ("image.jpg", image_bytes, "image/jpeg")},
                data={"size": "auto"},
                headers={"X-Api-Key": REMOVE_BG_API_KEY},
            )
            if response.status_code == 200:
                subject_image = Image.open(io.BytesIO(response.content)).convert("RGBA")
                subject_image = subject_image.resize((width, height))
        except Exception as e:
            print(f"Remove.bg error: {e}")

        # Step 3 — Color grade layer banao
        color_grade = Image.new("RGBA", (width, height), (0, 128, 128, 50))

        # Step 4 — Vignette layer banao
        vignette = Image.new("RGBA", (width, height), (0, 0, 0, 0))
        draw = ImageDraw.Draw(vignette)
        for i in range(min(width, height) // 2):
            opacity = int(120 * i / (min(width, height) // 2))
            draw.rectangle([i, i, width-i, height-i], outline=(0, 0, 0, opacity))
        vignette = vignette.filter(ImageFilter.GaussianBlur(radius=30))

        # Step 5 — Layers data collect karo
        layers_data = []

        # Background
        bg_buffer = io.BytesIO()
        original_image.save(bg_buffer, format="PNG")
        layers_data.append(("Background", bg_buffer.getvalue()))

        # Subject (if extracted)
        if subject_image:
            sub_buffer = io.BytesIO()
            subject_image.save(sub_buffer, format="PNG")
            layers_data.append(("Subject_Masked", sub_buffer.getvalue()))

        # Color grade
        cg_buffer = io.BytesIO()
        color_grade.save(cg_buffer, format="PNG")
        layers_data.append(("Color_Grade", cg_buffer.getvalue()))

        # Vignette
        vig_buffer = io.BytesIO()
        vignette.save(vig_buffer, format="PNG")
        layers_data.append(("Vignette", vig_buffer.getvalue()))

        # ZIP mein sab layers pack karo
        import zipfile
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
            for layer_name, layer_data in layers_data:
                zf.writestr(f"{layer_name}.png", layer_data)

            instructions = """LayerAI — Layer Export
==============================

HOW TO USE IN PHOTOSHOP:
1. Open Photoshop
2. File > Scripts > Load Files into Stack
3. Select all PNG files from this ZIP
4. Each file is a separate layer:
   - Background.png → Bottom layer (Normal, 100%)
   - Subject_Masked.png → Above background (Normal, 100%)
   - Color_Grade.png → Overlay blend mode, 75% opacity
   - Vignette.png → Multiply blend mode, 40% opacity
5. Arrange layers in this order (bottom to top):
   Background > Subject_Masked > Color_Grade > Vignette

Generated by LayerAI — layerai.app
"""
            zf.writestr("HOW_TO_USE.txt", instructions)

        zip_buffer.seek(0)
        return send_file(
            zip_buffer,
            mimetype="application/zip",
            as_attachment=True,
            download_name="layerai-layers.zip"
        )

    except Exception as e:
        print(f"Error: {e}")
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)
